### ISSUE TITLE
Service Provider specified Requested Authentication Context

### ISSUE THREAD

**Issue by adborden** [keitaroinc/ckanext-saml2auth#24]
In order to specify additional requirements to the Idp for the authentication context, Data.gov would like a way to customize the SAML2 RequestedAuthnContext, either through configuration or plugin extension .

## Background

In order to require a higher level of [authentication assurance](https://developers.login.gov/saml/#specifying-attributes-and-assurance-levels), we need to be able to specify additional elements for the RequestedAuthnContext.

AFAICT, pySAML2 doesn't provide this through configuration, it has to be done through code on a per-login basis. I believe it would be implemented with additional parameters to the [client.prepare_for_authenticate()](https://github.com/keitaroinc/ckanext-saml2auth/blob/5802c2a39246caa983a1b8b0c603f1b7a761566f/ckanext/saml2auth/views/saml2auth.py#L162). I haven't tested this:
```python
def saml2login():
    client = h.saml_client(sp_config())
    requested_authn_context = None
    if config.get('saml2auth.requested_authn_context'):
        requested_authn_context = samlp.RequestedAuthnContext()
        prepare_kwargs['requested_authn_context'] = requested_authn_context
        for item in config.get('saml2auth.requested_authn_context', []):
            context_class_ref = saml.AuthnContextClassRef()
            context_class_ref.text = item
        requested_authn_context.authn_context_class_ref.append(context_class_ref)

    reqid, info = client.prepare_to_authenticate(requested_authn_context=requested_authn_context)
    # ...
```

I think this would be a good candidate for an [ISaml2Auth interface](https://github.com/keitaroinc/ckanext-saml2auth/issues/13) since I imagine the Service Provider might want to modify the request directly instead of having to work with strings in the CKAN config.

**Comment by mbocevski** [comment]
When using AuthnContextClassRef in most cases one would likely also want to use the `Comparison` attribute that which would be defined in the `RequestedAuthnContext`. I need to think this through, but at first thought, it feelslike it's a better candidate for the interface.

`pysaml2` has all the support and yes passing additional parameters to [client.prepare_for_authenticate()](https://github.com/keitaroinc/ckanext-saml2auth/blob/5802c2a39246caa983a1b8b0c603f1b7a761566f/ckanext/saml2auth/views/saml2auth.py#L162) would work.

**Comment by avdata99** [comment]
Using the config approach I created #26 @adborden @mbocevski 
I also moved Travis to GitHub action because Travis no longer exists for this project.
It's working

**Comment by mbocevski** [comment]
Closing as #26 implements this fully.
