### ISSUE TITLE
PyPi package not published

### ISSUE THREAD

**Issue by killswitch-GUI** [keitaroinc/ckanext-saml2auth#40]
Documentation has this plugin published to PyPi for pip install. Right now we are installing via a tag using pips VCS egg install:

```bash
pip install -e "git+https://github.com/keitaroinc/ckanext-saml2auth.git@v1.0.1#egg=ckanext-saml2auth"
```

I know this is plugin is relatively new and documentation may not be updated.

**Comment by mbocevski** [comment]
Thanks @killswitch-GUI, you're right. We have now created the right config to publish to pypi and have published the [latest release](https://github.com/keitaroinc/ckanext-saml2auth/releases/tag/v1.0.2) on [pypi](https://pypi.org/project/ckanext-saml2auth/). So you can now install this extension simply by using `pip install ckanext-saml2auth`.

Please check it out and if all is fine we can close this issue.

**Comment by mbocevski** [comment]
Closing the issue considering the pypi publishing is in place including an automated release process through github actions.

**Comment by killswitch-GUI** [comment]
Thanks @mbocevski
