### ISSUE TITLE
Send logout request to IdP

### ISSUE THREAD

**Issue by FuhuXia** [keitaroinc/ckanext-saml2auth#49]
**Is your feature request related to a problem? Please describe.**
After a user logs out but leaves the browser tab open, clicking the login button will log the user back in without asking for credentials. 

**Describe the solution you'd like**
After a local logout or session time out, direct browser to the IdP logout URL with a SAMLRequest.  IdP will kill its session and redirect back with a POST request to SP's registered Assertion Consumer Service Logout URL.

**Additional context**
This is not necessarily a SLO request.

**Comment by mbocevski** [comment]
I'm guessing you're referring to some kind of a 'simple logout', however not a lot of IdPs out there support this kind of use case. I would rather think that it's better to implement SLO (and simpler) and when the user clicks logout that a SLO process starts. WDYT?

**Comment by FuhuXia** [comment]
Yes. "Simple logout" rather than "Single logout (SLO)" is being requested. Which one is a better use case is debatable. The IdP we are using happens to support [only "Simple logout"](https://developers.login.gov/saml/#logout). If we cant support both and make them configurable, then "Simple logout" is preferred. Thanks.

**Comment by pjsharpe07** [comment]
This may be out of the context of this issue, but it would be great if there was logging around user details during this logout process, similar to the login process if possible.

Please let me know if I need to create a separate issue. Thanks!

**Comment by mbocevski** [comment]
Once we complete #51 wit ill address this issue and provide this functionality through utilizing the "normal" SLO pysaml functionality.

**Comment by mbocevski** [comment]
Resolved by #51 and available on [pypy](https://pypi.org/project/ckanext-saml2auth/1.2.0/) through [release v1.2.0](https://github.com/keitaroinc/ckanext-saml2auth/releases/tag/v1.2.0)
