### ISSUE TITLE
[BUG ]logging out with version 1.2.0 logs out of IDP but not CKAN

### ISSUE THREAD

**Issue by chris48s** [keitaroinc/ckanext-saml2auth#55]
**Describe the bug**
After upgrading to version 1.2.0 of this plugin, the new SLO behaviour added in https://github.com/keitaroinc/ckanext-saml2auth/pull/51 logs me out of a Microsoft account using SAML2, but after the "logout" if I navigate back to the CKAN site I'm still logged in. This is because the CKAN cookies are not being expired/deleted before redirecting to the external provider to logout.
I am using `ckanext.saml2auth.logout_expected_binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"`.

**ckanext-saml2auth version affected**
v1.2.0

**Expected behaviour**
Logging out logs me out of CKAN itself and the external identity provider.
I guess roughly speaking the solution to this should be that the `/slo` endpoint should expire/delete the CKAN cookie before calling `toolkit.redirect_to(u'user.logout')` but I'm not exactly sure how to achieve this. Under older CKAN versions the pylons response object was exposed on the plugin toolkit, so it would have been possible to call `toolkit.response.delete_cookie()` in `slo()` but in CKAN >=2.9 the flask response object is not exposed on the toolkit, making this trickier to achieve.

**Comment by Panzki** [comment]
Hi,
I encountered a similar issue recently. I was trying to use the SLO feature with the HTTP-Redirect binding as well. When trying to log out, CKAN would redirect me to the identity provider correctly and the identity provider did perform a log out on its site. Then the identity provider would perform a redirect to the `/slo` endpoint. The Blueprint that handles the call to the `slo` endpoint then performs a redirect to CKANs logout page.

https://github.com/keitaroinc/ckanext-saml2auth/blob/b826d0ae69ca34008c9005231a05e4627175d630/ckanext/saml2auth/views/saml2auth.py#L319-L323

For me this results to another redirect to the identity provide, which then will do another redirect the `/slo` endpoint and so on. If I then reload the CKAN home page I'm still logged in. I think this is the result of how CKAN executes the logout of the plugin. The [CKAN docs](https://docs.ckan.org/en/2.9/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IAuthenticator.logout) state that the logout function is "Called before the logout starts", which probably causes the infinite loop.

I can not provide a fix for the SLO probems (yet).  However I have an idea for a possible solution, maybe this helps to fix the problems. The `/slo` endpoint receives a SAML logout response from the identity provider as an URL parameter. Some thing like [this](https://www.samltool.com/generic_slo_res.php). I think the controller function of the `/slo` endpoint should evaluate this response. If the response states that the logout was successful, I think we should not redirect the user to the logout endpoint (again), but rather emulate the CKAN logout behavior and redirect the user to the `logout_handler_path`. Here is the [relevant code from the CKAN](https://github.com/ckan/ckan/blob/077656c55ac257bfda5761a9a044777d47961850/ckan/views/user.py#L484-L494) repository.
To evaluate the SAML logout response pysamle may provide some functionality, so we do not have to build this.

I hope this wall of text makes sense and maybe it is helpful.

**Comment by amercader** [comment]
This is a serious issue. I've submitted https://github.com/keitaroinc/ckanext-saml2auth/pull/56 with a potential fix

**Comment by mbocevski** [comment]
We are reviewing this and once fixed we will publish a new version.

**Comment by mbocevski** [comment]
Fixed in version 1.2.1
