### ISSUE TITLE
How to generate the sp.xml 

### ISSUE THREAD

**Issue by gurinderpal-lnwebworks** [keitaroinc/ckanext-saml2auth#63]
How to generate the sp.xml with this extension

**Comment by duskobogdanovski** [comment]
Hi @gurinderpal-lnwebworks, what's the reason you need sp.xml?

**Comment by gurinderpal-lnwebworks** [comment]
i need to connect the ckan with gluu. So at ckan end i need sp.xml .
I have already idp.xml from gluu end

**Comment by duskobogdanovski** [comment]
Sorry that we don't have that part described into our extension but i guess you can use [make_metadata.py](https://github.com/IdentityPython/pysaml2/blob/v6.5.1/tools/make_metadata.py) as it is noted in this [guide](https://pysaml2.readthedocs.io/en/latest/howto/config.html#configuration-of-pysaml2-entities). The configuration for the SP side can be found [here](https://github.com/keitaroinc/ckanext-saml2auth/blob/main/ckanext/saml2auth/spconfig.py).
