### ISSUE TITLE
ValueError: Missing assertion /python3.8/site-packages/saml2/response.py line 745, in get_subject

### ISSUE THREAD

**Issue by pankshiks** [keitaroinc/ckanext-saml2auth#64]
**Describe the bug**
ValueError: Missing assertion

This is my saml response 

<?xml version="1.0" encoding="UTF-8"?>
<saml2p:Response
	xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://testckan.abraxasint.com/sso/post" ID="_4052f8d933b98e7ddd4a3b8115cc7c3c" IssueInstant="2021-12-23T11:15:29.375Z" Version="2.0">
	<saml2:Issuer
		xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">https://elkgluustage.abraxasint.com/idp/shibboleth
	</saml2:Issuer>
	<ds:Signature
		xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
		<ds:SignedInfo>
			<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
			<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
			<ds:Reference URI="#_4052f8d933b98e7ddd4a3b8115cc7c3c">
				<ds:Transforms>
					<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
					<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
				</ds:Transforms>
				<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
				<ds:DigestValue>GUrF75jyGot6qNYY/X35ZwVgfdEgqgqXl3f+WzksDxg=</ds:DigestValue>
			</ds:Reference>
		</ds:SignedInfo>
		<ds:SignatureValue>b/JV1FjOWQLbHCCvuohrS+QccYaC/qBnPBjRv/WEWacMkZc9paThqjAlKU0dJq4JPklGSdcZAiH0o+ecR78LMvT1VPzbGX0pcw2aHSiOmkezh6vCZgpsiUxMlvXSmFeOtqow6Y+SSCLFM5BhtZATFsnsIuEwRBeYhftdHJQSWUn1ZGVIkrObBMMKEqevdPTmK3h1k0RjqHwhQtTMZMBI1duL18wZI6bZEkjhJl5L0EEgRBgLL8L1B3FpFLOzRCQh6ybm2oei+a8xvLlMurU9+D+JjrYbfgCr+bFNfhN8Y6kny6xli2OhOd0iazd1kyjb7zwxb8M7tTl/o9o1EeQbOQ==</ds:SignatureValue>
		<ds:KeyInfo>
			<ds:X509Data>
				<ds:X509Certificate>MIIDnzCCAocCFGegBIVhYiABIFrcgH1bu7voSQbWMA0GCSqGSIb3DQEBCwUAMIGLMQswCQYDVQQG
EwJDQTELMAkGA1UECAwCT04xEDAOBgNVBAcMB1Rvcm9udG8xDzANBgNVBAoMBkNDUkVFRTEkMCIG
A1UEAwwbZWxrZ2x1dXN0YWdlLmFicmF4YXNpbnQuY29tMSYwJAYJKoZIhvcNAQkBFhdhYWxsZXlu
ZUBhYnJheGFzaW50LmNvbTAeFw0yMTAzMTYxNTUxNDRaFw0yMjAzMTYxNTUxNDRaMIGLMQswCQYD
VQQGEwJDQTELMAkGA1UECAwCT04xEDAOBgNVBAcMB1Rvcm9udG8xDzANBgNVBAoMBkNDUkVFRTEk
MCIGA1UEAwwbZWxrZ2x1dXN0YWdlLmFicmF4YXNpbnQuY29tMSYwJAYJKoZIhvcNAQkBFhdhYWxs
ZXluZUBhYnJheGFzaW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALG8uVKE
AZ9XZxj3vQ19LvRN/dZOmRP/+5H24X7xAd4PF1L3x9pMDP60iYoAgdRofetGVU5iDqpFupZQqy8z
mWfu0GP669g2c3IWCAFU9YTmDHajb3vGaxbhKN4vgkJMr25uQxAUrUgNPNPC12gREzwreTBqmIT0
odptEgRbGOu3vPKdTSQDbZLirpR6GJKnUFj/sapK/zblRiQB0oylemA1Rn9DXZf6mDKGQZ94haUR
Cjlp1SxNOi9UT084cQPa0FyKw79zqUWZbmUPlkp7hbU5wN2+8Ut9NfArrQntdxWa9KjGPnaS0rMZ
OT0k8CfHiSJYxpEQI194dlw6mnwpqF0CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAF/s+7B2lhHh2
ANq/O9UpNnTh2qt/5ePernJebycHSgJrbzSQ4TqrUReepmqfjBiuMfSrbXju58dQSW5AAW+VIEWW
fGTsTFGmZTRLfI3fbrKhQKkTqYuhDfm4G9kgyJoIK9jBAi4JYKtIiplWPulzYkcyA/re7UDdZU8D
mtzTSYhFeILv8UDPDqIAehxFK25/Eg5DVRTSrexRnwjGj2AS402foOX7W1igky841JvCNZBLSVwj
Aq5OKnAZgqnmQ5NGRFlhnBMiNRt2HZ27TTC4RrqEnjO1UX5Fgg6LT5IvLRoRoid0DYbkFmP6dvWd
Q4GqYFpuoiE6j5STew5k2ZiJUQ==</ds:X509Certificate>
			</ds:X509Data>
		</ds:KeyInfo>
	</ds:Signature>
	<saml2p:Status>
		<saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
	</saml2p:Status>
	<saml2:Assertion
		xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="_c9fa2a523188bba70d26581678fdfc39" IssueInstant="2021-12-23T11:15:29.375Z" Version="2.0">
		<saml2:Issuer>https://elkgluustage.abraxasint.com/idp/shibboleth</saml2:Issuer>
		<ds:Signature
			xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
			<ds:SignedInfo>
				<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
				<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
				<ds:Reference URI="#_c9fa2a523188bba70d26581678fdfc39">
					<ds:Transforms>
						<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
						<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
					</ds:Transforms>
					<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
					<ds:DigestValue>aDaP5VkPGcBjsGlcVVzjjSWAYv9wx/d9Uy5VkB/6O98=</ds:DigestValue>
				</ds:Reference>
			</ds:SignedInfo>
			<ds:SignatureValue>o1CDFLwfYoEJT5os5bHOMrX2grtIEsFjBOWlIY5ou+Ksqi8wxbJjDgMzbf0AhXOpVbfBC6BX6vILc3hYD5IKE8nSkSTCjH/3Z4WYFpbSBMuifoLcDHr6bXiFQ0Vq1uz3zPaf1pKFv/qQKJY8kWYoFv70zI4arU92cyiVNR5IbWU9SSU6zBQOsGIqg1WgvVeJFbST2I4d09PqjA3qMhdh0/AOW2gm1Z5CEwKk+VsSusdEW8i2rAGCd5++Xx2HqaXORHJIKx7fGeSr+4EIM/YlHpqTMkUUEW9PyjfktbO8DGTMZ0F59Qp1+fAs713XPoU7zZLztBdM8HbNBUATnMB3TA==</ds:SignatureValue>
			<ds:KeyInfo>
				<ds:X509Data>
					<ds:X509Certificate>MIIDnzCCAocCFGegBIVhYiABIFrcgH1bu7voSQbWMA0GCSqGSIb3DQEBCwUAMIGLMQswCQYDVQQG
EwJDQTELMAkGA1UECAwCT04xEDAOBgNVBAcMB1Rvcm9udG8xDzANBgNVBAoMBkNDUkVFRTEkMCIG
A1UEAwwbZWxrZ2x1dXN0YWdlLmFicmF4YXNpbnQuY29tMSYwJAYJKoZIhvcNAQkBFhdhYWxsZXlu
ZUBhYnJheGFzaW50LmNvbTAeFw0yMTAzMTYxNTUxNDRaFw0yMjAzMTYxNTUxNDRaMIGLMQswCQYD
VQQGEwJDQTELMAkGA1UECAwCT04xEDAOBgNVBAcMB1Rvcm9udG8xDzANBgNVBAoMBkNDUkVFRTEk
MCIGA1UEAwwbZWxrZ2x1dXN0YWdlLmFicmF4YXNpbnQuY29tMSYwJAYJKoZIhvcNAQkBFhdhYWxs
ZXluZUBhYnJheGFzaW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALG8uVKE
AZ9XZxj3vQ19LvRN/dZOmRP/+5H24X7xAd4PF1L3x9pMDP60iYoAgdRofetGVU5iDqpFupZQqy8z
mWfu0GP669g2c3IWCAFU9YTmDHajb3vGaxbhKN4vgkJMr25uQxAUrUgNPNPC12gREzwreTBqmIT0
odptEgRbGOu3vPKdTSQDbZLirpR6GJKnUFj/sapK/zblRiQB0oylemA1Rn9DXZf6mDKGQZ94haUR
Cjlp1SxNOi9UT084cQPa0FyKw79zqUWZbmUPlkp7hbU5wN2+8Ut9NfArrQntdxWa9KjGPnaS0rMZ
OT0k8CfHiSJYxpEQI194dlw6mnwpqF0CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAF/s+7B2lhHh2
ANq/O9UpNnTh2qt/5ePernJebycHSgJrbzSQ4TqrUReepmqfjBiuMfSrbXju58dQSW5AAW+VIEWW
fGTsTFGmZTRLfI3fbrKhQKkTqYuhDfm4G9kgyJoIK9jBAi4JYKtIiplWPulzYkcyA/re7UDdZU8D
mtzTSYhFeILv8UDPDqIAehxFK25/Eg5DVRTSrexRnwjGj2AS402foOX7W1igky841JvCNZBLSVwj
Aq5OKnAZgqnmQ5NGRFlhnBMiNRt2HZ27TTC4RrqEnjO1UX5Fgg6LT5IvLRoRoid0DYbkFmP6dvWd
Q4GqYFpuoiE6j5STew5k2ZiJUQ==</ds:X509Certificate>
				</ds:X509Data>
			</ds:KeyInfo>
		</ds:Signature>
		<saml2:Subject>
			<saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
				<saml2:SubjectConfirmationData Address="112.196.0.226" NotOnOrAfter="2021-12-23T11:20:29.382Z" Recipient="https://testckan.abraxasint.com/sso/post"/>
			</saml2:SubjectConfirmation>
		</saml2:Subject>
		<saml2:Conditions NotBefore="2021-12-23T11:15:29.375Z" NotOnOrAfter="2021-12-23T11:20:29.435Z">
			<saml2:AudienceRestriction>
				<saml2:Audience>http://testckan.abraxasint.com:8090/ckan_sp.xml</saml2:Audience>
			</saml2:AudienceRestriction>
		</saml2:Conditions>
		<saml2:AuthnStatement AuthnInstant="2021-12-23T10:35:23.586Z" SessionIndex="_0ee9767f27b75ed90d4d0569f3dab79e">
			<saml2:SubjectLocality Address="112.196.0.226"/>
			<saml2:AuthnContext>
				<saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml2:AuthnContextClassRef>
			</saml2:AuthnContext>
		</saml2:AuthnStatement>
		<saml2:AttributeStatement>
			<saml2:Attribute FriendlyName="sn" Name="urn:oid:2.5.4.4" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<saml2:AttributeValue>LastName</saml2:AttributeValue>
			</saml2:Attribute>
			<saml2:Attribute FriendlyName="givenName" Name="urn:oid:2.5.4.42" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<saml2:AttributeValue>FirstName</saml2:AttributeValue>
			</saml2:Attribute>
			<saml2:Attribute FriendlyName="mail" Name="urn:oid:0.9.2342.19200300.100.1.3" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
				<saml2:AttributeValue>username@gmail.com</saml2:AttributeValue>
			</saml2:Attribute>
		</saml2:AttributeStatement>
	</saml2:Assertion>
</saml2p:Response>

**ckanext-saml2auth version affected**
v1.1.0

**Expected behaviour**

**Logs**
If applicable, add logs to help explain your problem.

**Comment by duskobogdanovski** [comment]
We will check this and get back with more details.

**Comment by jeromethibault** [comment]
I'm facing the same issue with v1.2.2.

When can we expect a fix ?

**Comment by iAce02** [comment]
Hello @pankshiks and @jeromethibault , I've checked the issue, but i wasn't able to replicate this.
This looks like configuration issue (missing or wrong entity ID or URL endpoint), can you share more info that can help resolve this? Ex. which provider are you using, something more on the configuration like local or remote , when exactly the exception raises (click on login, after entering username..) Thank you
