### ISSUE TITLE
[BUG] things continue to work with wrong mycert.pem

### ISSUE THREAD

**Issue by FuhuXia** [keitaroinc/ckanext-saml2auth#67]
**Describe the bug**
`ckanext.saml2auth.cert_file_path = /path/to/mycert.pem`

The content of mycert.pem does not matter, at least in our setup. The file still need to be present, the content still need to look like a certificate, but it will work with content like this.
```
-----BEGIN CERTIFICATE-----
placeholder
-----END CERTIFICATE-----
```
**ckanext-saml2auth version affected**
v1.1.0

**Expected behaviour**
Something missing in the README for this behaviour?

**Comment by mixmixmix** [comment]
Are you sure you have set 
```
  ckanext.saml2auth.want_response_signed = True
  ckanext.saml2auth.want_assertions_signed = True
```
I think that you set them to `False` it might behave this way.

**Comment by mixmixmix** [comment]
Thanks for feedback @FuhuXia ! I'm just trying to understand the problems I have implementing this at the moment (this one was one of them) and incidentally, was at the point upgrading to 10.4 as well!
