### ISSUE TITLE
Not working when CKAN is not mounted on root of Webserver

### ISSUE THREAD

**Issue by sobiero** [keitaroinc/ckanext-saml2auth#73]
Not working when CKAN is not mounted on the root of the webserver e.g. `https://www.example.org/ckan/` 

IDP response is directed to the root `https://www.example.org/acs` instead of `https://www.example.org/ckan/acs`

The module should read the setting `ckan.root_path` as described in https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-root-path

**Comment by duskobogdanovski** [comment]
Hi @sobiero , this is not an issue with the extension, you can change this behavior with the following setting:

- URL route of the endpoint where the SAML assertion is sent, also known as Assertion Consumer Service (ACS).
- Default: /acs
ckanext.saml2auth.acs_endpoint = /sso/post

**Comment by sobiero** [comment]
@duskobogdanovski I have used `/sso/post` but it still directs to `https://www.example.org/sso/post` instead of `https://www.example.org/ckan/sso/post`. I tried `ckanext.saml2auth.acs_endpoint =/ckan/sso/post` but this leads to a 405 error. Is there something I am not doing right ?

**Comment by sobiero** [comment]
@duskobogdanovski 
On the file `/ckanext/saml2auth/spconfig.py`, changing line 32 to below seems to work for me. 
`base = ckan_config.get('ckan.site_url') + ckan_config.get('ckan.root_path').replace("{{LANG}}", "" )`
my ckan.root_path is: `ckan.root_path=/ckan/{{LANG}}`

**Comment by sobiero** [comment]
@duskobogdanovski @dumyan 
In the file /ckanext/saml2auth/spconfig.py, changing line 32 to below seems to work for me.
base = ckan_config.get('ckan.site_url') + ckan_config.get('ckan.root_path').replace("{{LANG}}", "" )
my ckan.root_path is: ckan.root_path=/ckan/{{LANG}}

**Comment by sobiero** [comment]
@duskobogdanovski @dumyan 
In the file `/ckanext/saml2auth/spconfig.py`, changing line 32 to below seems to work for me.
`base = ckan_config.get('ckan.site_url') + ckan_config.get('ckan.root_path').replace("{{LANG}}", "" )`
my ckan.root_path is: `ckan.root_path=/ckan/{{LANG}}`
