### ISSUE TITLE
[BUG] Auth Cookies Not Removed On Logout

### ISSUE THREAD

**Issue by OfficialOwlElder** [keitaroinc/ckanext-saml2auth#91]
**Describe the bug**
Upon logging out of my CKAN instance, the authentication cookies are not removed. This seems to be identical to #68. I tried the fix that they suggested by making this change in plugin.py:
from
`response.set_cookie('auth_tkt', domain=domain, expires=0)`
to
`response.set_cookie('auth_tkt', expires=0)`

Similar to #68, I also had to change the ckanext.saml2auth.logout_expected_binding to urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect as urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST was causing an Internal Server Error.

Here is all of my relevant ckanext-saml2 configurations from ckan.ini
``` 
# Specifies the metadata location type
# Options: local or remote
ckanext.saml2auth.idp_metadata.location = local

# Path to a local file accessible on the server the service runs on
# Ignore this config if the idp metadata location is set to: remote
ckanext.saml2auth.idp_metadata.local_path = /opt/metadata/some.xml

# Path to a local file accessible on the server the service runs on
# Ignore this config if the idp metadata location is set to: local and metadata is public
ckanext.saml2auth.idp_metadata.remote_cert = /opt/metadata/some.cert

# Corresponding SAML user field for firstname
ckanext.saml2auth.user_firstname = givenName

# Corresponding SAML user field for lastname
ckanext.saml2auth.user_lastname = surname

# Corresponding SAML user field for email
ckanext.saml2auth.user_email = emailAddress

# Entity ID (also know as Issuer)
# Define the entity ID. Default is urn:mace:umu.se:saml:ckan:sp
ckanext.saml2auth.entity_id = https://subdomain.domain.com/ckan/
ckanext.saml2auth.want_response_signed = False
ckanext.saml2auth.want_assertions_signed = True
ckanext.saml2auth.want_assertions_or_response_signed = True

# URL route of the endpoint where the SAML assertion is sent, also known as Assertion Consumer Service (ACS).
# Default: /acs
ckanext.saml2auth.acs_endpoint = /acs/

# Indicates if this entity will sign the Logout Requests originated from it
#ckanext.saml2auth.logout_requests_signed = True

# Saml logout request preferred binding settings variable
# Default: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
ckanext.saml2auth.logout_expected_binding =  urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
````

**ckanext-saml2auth version affected**
v1.3.0

**CKAN Core version**
2.10.1

**Expected behaviour**
Upon clicking the logout button, the browser should redirect to the SLO page and remove the authentication cookie forcing the user to login again.

**Comment by pdelboca** [comment]
@OfficialOwlElder which cookie are you trying to clean? `auth_tkt` has been removed in CKAN 2.10 if favor of `ckan` cookie.

**Comment by OfficialOwlElder** [comment]
Hi @pdelboca, I'm not 100% familiar with how the SAML2 login/CKAN login cookies work, but to the best of my understanding, there should be a cookie created upon logging in and that cookie should be deleted/invalidated upon logging out. Currently, when a user logs out they are forwarded to a SAML2 logout page that says that they have logged out successfully. If they try going back to our CKAN page after this, they are still logged in. 

Does this mean that I should modify this
`response.set_cookie('auth_tkt', domain=domain, expires=0)`

to this:
`response.set_cookie('ckan', domain=domain, expires=0)`

**Comment by pdelboca** [comment]
Yes @OfficialOwlElder you should update that. Also, you can use the browser to check which cookies are being created upon login. If you have an `auth_tkt` cookie is because maybe some old code is still setting it. This could happen if the instance was migrated from `2.9` to `2.10`.

When logging out, the `ckan` cookie will still exist, but its value would have change.

### Cookies created upon login
CKAN: `ckan`, `remember_me`
FlaskDebutToolbar: `fldt`

![image](https://github.com/keitaroinc/ckanext-saml2auth/assets/6672339/473b5ae3-caeb-40bb-8be7-8d6ce76c378e)

**Comment by tino097** [comment]
Regarding the Azure issue, my latest test redirected to ckan logout but because in azure it is required to set the `logout_url` with HTTPS , action failed. 

@Filip3mac @blagojabozinovski please check on your side too, but as @pdelboca mentioned, clean all the cookies before testing

**Comment by OfficialOwlElder** [comment]
@pdelboca weirdly enough, I only see the ckan cookie when I login. I am using CKAN version 2.10.1. Currently I have none of the cookie configuration in my ckan.ini file. Is it possible that I need to configure the cookie settings to display the remember_me cookie/delete it upon logout?

**Comment by OfficialOwlElder** [comment]
If I delete the ckan cookie manually, it is successfully logging me out. I looked again at the logout function in plugin.py and it seems that the ckan cookie should be getting deleted, but it's not.

![image](https://github.com/keitaroinc/ckanext-saml2auth/assets/22074181/e5914941-ada7-4b42-96bf-9d2db6560bf3)

If I look at the logs, the saml2 extension seems to think that the logout was successful.
<img width="1035" alt="image" src="https://github.com/keitaroinc/ckanext-saml2auth/assets/22074181/d2c85ff3-dbb2-4f31-aa4d-baf4b2431d28">

I spoke with my colleague who manages our Azure SSO and he tried creating a logout page in the SSO settings for our application and suggested that I enable signed logouts as such:
<img width="536" alt="image" src="https://github.com/keitaroinc/ckanext-saml2auth/assets/22074181/d8141361-2f32-4c33-adae-7b3ab8a3f0c5">

But when I enable this setting, I start to get this error:
<img width="812" alt="image" src="https://github.com/keitaroinc/ckanext-saml2auth/assets/22074181/1aba891f-cf8c-4c98-8cb4-49b9abd09951">

**Comment by PortarescuOctavian** [comment]
@amercader I have the same problem, but deleting the cookie works perfectly, why didn't you use delete cookie?

**Comment by OfficialOwlElder** [comment]
The problem seems to be with the domain field of of the set_cookie. In my ckan configuration I have
`beaker.session.cookie_domain = .subdomain.domain.com`
`ckan.site_url = https://my-ckan-page.subdomain.domain.com`

Some how the domain parameter is getting my-ckan-page.subdomain.domain.com instead of .subdomain.domain.com

If I hard code the domain in the domain field the problem is resolved. Is it possible that I have configured my site_url and cookie_domain incorrectly, or is this a bug with subdomains?

**Comment by OfficialOwlElder** [comment]
I must apologize for my ignorance as I now understand that the first part of the URL is itself also a subdomain. I was able to resolve the issue by updating my beaker.session.cookie_domain to:
`beaker.session.cookie_domain = my-ckan-page.subdomain.domain.com`

I did not realize that the 'my-ckan-page' portion is a subdomain.

Closing this issue, thank you for your support.
